### DISCUSSION TITLE
Problem bringing Yourls service up

### DISCUSSION THREAD

**Discussion by diggidre** [YOURLS/YOURLS#2906] [General]
Hey guys,
I have a problem with starting yourls container.
I followed the docker hub description but when I go to my yourls sub I get an Error 504.
The yourls container log says
MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known
I use docker on raspbian that runs on a pi4b with traefik v1.7.30 and nextcloud 21 already up and running.
Here is my yourls docker-compose.yml

```yaml
version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    ports:
      - 8008:80 # 8080 is already in use
    environment:
      YOURLS_DB_PASS: xxx
      YOURLS_SITE: https://sub.mydomain.xxx
      YOURLS_USER: root
      YOURLS_PASS: xxx
      YOURLS_DB_HOST: name of the mariadb service > same as I use for nextcloud
      YOURLS_DB_NAME: yourls
      
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sub.mydomain"
      - "traefik.frontend.rule=Host:sub.mydomain.xxx"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"
            
    networks:
      - traefik
      
networks:
  traefik:
    external:
      name: traefik
  default:
    driver: bridge
```

sry could not pastebin the code because pastebin says code is potentially offensiv ...
