### DISCUSSION TITLE
How to start YOURLS locally? (in docker)

### DISCUSSION THREAD

**Discussion by uinstinct** [YOURLS/YOURLS#2923] [Q&A] [answered]
I was redirected to this url (http://your-own-domain-here.com/admin/install.php) when I tried to start Yourls locally in docker.

My docker-compose file was this:
```yml
version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    container_name: yourls-site-1
    ports:
      - 7777:80
    environment:
      YOURS_SITE: http://localhost
      YOURLS_DB_PASS: yourlsdbpass
      YOURLS_USER: admin
      YOURLS_PASS: yourlspass

  mysql:
    container_name: yourls-db-1
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourlsdbpass
```

I can't figure out what to do. **Is there a way to start YOURLS locally?** (I am using Ubuntu 20.04)

**Comment by dgw** [comment, marked as answer]
> `YOURS_SITE`

Try fixing this typo.

**Reply by uinstinct** [reply]
@dgw Thanks for replying to my question and for helping me out. 🎉

There was another mistake that I had done.
I had to change **`http://localhost:7777`** instead of `http://localhost`

This is my final working docker-compose.yml
```yaml
version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    container_name: yourls-site-1
    ports:
      - 7777:80
    environment:
      YOURLS_SITE: http://localhost:7777
      YOURLS_DB_PASS: yourlsdbpass
      YOURLS_USER: admin
      YOURLS_PASS: yourlspass

  mysql:
    container_name: yourls-db-1
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourlsdbpass
 ```
