### DISCUSSION TITLE
Traefik revers proxy setup

### DISCUSSION THREAD

**Discussion by jwillmer** [YOURLS/YOURLS#2992] [Q&A] [answered]
I try to setup YOURLS behind a revers proxy to enable HTTPS (only) but every page I try to open returns a `404`:

```
https://example.com/admin
https://example.com/admin/index.php
https://example.com/index.php 
```

That is the output I see in the YOURLS log:

```
Warning: Undefined array key 1 in Standard input code on line 8
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.5. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.5. Set the 'ServerName' directive globally to suppress this message
[Wed Jul 14 07:39:30.137278 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/8.0.8 configured -- resuming normal operations
[Wed Jul 14 07:39:30.137468 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

 Below is my docker-compose file. The `DOMAINNAME` is a root domain like `example.com` not a subdomain if that matters.

```
version: '3.5'

networks:
    traefik_proxy:
        name: traefik_proxy
    backend:
        name: backend

volumes:
  mysql:
    
services:

  traefik:
    image: traefik:v2.4
    container_name: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" 
      - "--providers.docker.network=traefik_proxy"       
      - "--entrypoints.https.address=:443"
    networks:
      - default
      - traefik_proxy
    ports:      
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
            
  yourls:
    image: yourls:1.8
    container_name: yourls
    restart: always
    networks:
      - backend
      - traefik_proxy
    environment:
      - YOURLS_DEBUG=true
      - YOURLS_DB_HOST=database
      - YOURLS_DB_USER=root
      - YOURLS_DB_PASS=${DB_PASSWORD}
      - YOURLS_DB_NAME=${DB_DATABASE}
      - YOURLS_SITE=https://${DOMAINNAME}
      - YOURLS_USER=${YOURLS_USER}
      - YOURLS_PASS=${YOURLS_PW}      
      - YOURLS_PRIVATE=true
      - YOURLS_COOKIEKEY=${YOURLS_COOKIEKEY}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.services.yourls.loadbalancer.server.port=80"
      - "traefik.http.routers.yourls.rule=Host(`${DOMAINNAME}`)"
      - "traefik.http.routers.yourls.entrypoints=https"
    links:
      - database

  database:
    image: mysql:5.7
    container_name: database
    restart: always    
    networks:
      - backend
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
```
