### DISCUSSION TITLE
Unable to launch Docker image

### DISCUSSION THREAD

**Discussion by goose-ws** [YOURLS/YOURLS#3226] [Q&A] [answered]
I'm trying to use the `fpm-alpine` docker image of YOURLS and having difficulty getting off the ground.

I'm using the following compose file:

```yaml
version: '3.1'

services:
  yourls:
    container_name: yourls
    hostname: yourls
    image: yourls:fpm-alpine
    # ports:
      # - 8080:80
    environment:
      - "YOURLS_DB_PASS=[redacted]"
      - "YOURLS_SITE=test.goose.ws"
      - "YOURLS_USER=goose"
      - "YOURLS_PASS=[redacted]"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    labels:
      - "com.ouroboros.enable=true"
    logging:
      driver: json-file
      options: 
        max-file: "3"
        max-size: "10M"
    network_mode: BucketNet

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=[redacted]"
      - "MYSQL_DATABASE=yourls"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    labels:
      - "com.ouroboros.enable=true"
    logging:
      driver: json-file
      options: 
        max-file: "3"
        max-size: "10M"
    network_mode: BucketNet
```

I have the port commented out because I'm reverse proxying to the container from a separate nginx container on the same `BucketNet` network.

`12-yourls.conf`:

```nginx
server {
  listen 80;
  listen [::]:80;
  server_name test.goose.ws;
  root /var/www/test.goose.ws;
  access_log /var/log/nginx/test.access.log;
  error_log /var/log/nginx/test.error.log;
  location / {
    return 301 https://test.goose.ws$request_uri;
  }
  location /.well-known/ {
    allow all;
  }
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name test.goose.ws;
  root /var/www/test.goose.ws;
  ssl_certificate /etc/letsencrypt/live/test.goose.ws/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/test.goose.ws/privkey.pem;
  access_log /var/log/nginx/test.access.log;
  error_log /var/log/nginx/test.error.log;

  location / {
    include proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app yourls;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /.well-known/ {
    allow all;
  }
}
```

The containers launch well:

```
[goose@Bucket: ~ ] $ docker logs yourls
YOURLS not found in /var/www/html - copying now...
Complete! YOURLS has been successfully copied to /var/www/html
chown: wp-config.php: No such file or directory
[16-Feb-2022 21:44:54] NOTICE: fpm is running, pid 1
[16-Feb-2022 21:44:54] NOTICE: ready to handle connections
[goose@Bucket: ~ ] $
```

However, when I try to go to the admin page, I'm greeted with a bad gateway error:

![image](https://user-images.githubusercontent.com/874014/154395464-09a650ca-6126-4d62-a638-f502cf66dfab.png)

It seems like an issue inside the container, if I bypass the reverse proxy and directly connect to the container IP, it still fails to connect to the httpd:

```
[goose@Bucket: ~ ] $ docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' yourls
172.18.0.16
[goose@Bucket: ~ ] $ curl -svL "http://172.18.0.16:80/admin/"
* Expire in 0 ms for 6 (transfer 0x55c1b3430fb0)
*   Trying 172.18.0.16...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55c1b3430fb0)
* connect to 172.18.0.16 port 80 failed: Connection refused
* Failed to connect to 172.18.0.16 port 80: Connection refused
* Closing connection 0
[goose@Bucket: ~ ] $
```

For what it's worth, the `nginx` container is resolving correctly, and results in the same output:

```
[goose@Bucket: ~ ] $ docker exec -it nginx curl -svL http://yourls:80/admin/
*   Trying 172.18.0.16:80...
* connect to 172.18.0.16 port 80 failed: Connection refused
* Failed to connect to yourls port 80: Connection refused
* Closing connection 0
[goose@Bucket: ~ ] $ 
```

Any suggestions on where I may have gone wrong?

**Comment by LeoColomb** [comment, marked as answer]
Hard to tell without a view on how `BucketNet` network is configured.
Plus, why is it setup as `network_mode:` and not as `networks: []`?

**Reply by goose-ws** [reply]
> Hard to tell without a view on how `BucketNet` network is configured.

It's a basic bridge network. Created with: `docker network create -d bridge --gateway "172.18.0.1" --subnet "172.18.0.0/24" BucketNet`

I removed the `network_mode` to put it on the default network:

```yaml
version: '3.1'

services:
  yourls:
    container_name: yourls
    hostname: yourls
    image: yourls:fpm-alpine
    # ports:
      # - 8080:80
    environment:
      - "YOURLS_DB_PASS=[redacted]"
      - "YOURLS_SITE=test.goose.ws"
      - "YOURLS_USER=goose"
      - "YOURLS_PASS=[redacted]"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    labels:
      - "com.ouroboros.enable=true"
    logging:
      driver: json-file
      options: 
        max-file: "3"
        max-size: "10M"
    # network_mode: BucketNet

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=[redacted]"
      - "MYSQL_DATABASE=yourls"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    labels:
      - "com.ouroboros.enable=true"
    logging:
      driver: json-file
      options: 
        max-file: "3"
        max-size: "10M"
    # network_mode: BucketNet
```

But the result is the same:

```
[goose@Bucket: ~ ] $ docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' yourls
172.20.0.2
[goose@Bucket: ~ ] $ curl -svL http://172.20.0.2:80/admin/
* Expire in 0 ms for 6 (transfer 0x5578f4059fb0)
*   Trying 172.20.0.2...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x5578f4059fb0)
* connect to 172.20.0.2 port 80 failed: Connection refused
* Failed to connect to 172.20.0.2 port 80: Connection refused
* Closing connection 0
[goose@Bucket: ~ ] $
```

> Plus, why is it setup as `network_mode:` and not as `networks: []`?

I didn't know that one was better than the other, so I just went with `network_mode` since it was shorter than a `networks: []` block.
