### DISCUSSION TITLE
Few questions about setting Caddy with yourls-fpm

### DISCUSSION THREAD

**Discussion by ghost** [YOURLS/YOURLS#3333] [Q&A]
**First of all, sorry for my poor english.**
**What I'm saying is maybe a little "Google".**

I'm new to the PHP and Caddy.
And I'm trying to add YOURLS to my server.
I want to use a existed Caddy because there are some web service is already runing.

https://caddy.community/t/v2-help-to-set-up-a-yourls-instance/7260
https://caddy.community/t/example-yourls/7908
I checked out these pages and I made a docker-compose.yaml & Caddyfile like these.

```yaml
version: "3.9"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somepass
      - MYSQL_DATABASE=somedbname
      - MYSQL_USER=someuser
      - MYSQL_PASSWORD=somepass
    volumes:
      - ./mysql:/var/lib/mysql
  
  yourls:
    image: yourls:fpm-alpine
    container_name: yourls
    restart: always
    environment:
      - YOURLS_DB_HOST=mysql:3306
      - YOURLS_DB_NAME=somedbname
      - YOURLS_DB_USER=someuser
      - YOURLS_DB_PASS=somepass
      - YOURLS_SITE=https://yourls.domain.com
      - YOURLS_USER=someuser
      - YOURLS_PASS=somepass
    depends_on:
      - mysql

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    depends_on:
      - yourls
```

```caddyfile
{
    debug
    email   nagaseyami@gmail.com
}

https://yourls.domain.com {
    root * /var/www/html
    route {        
        try_files {path} {path}/index.php yourls-loader.php
        php_fastcgi yourls:9000
    }
    file_server
}
```
It works. But a little weird.
It can't automatically redirect to `yourls-loader.php` or `index.php` when I access `https://yourls.domain.com` or `https://yourls.domain.com/admin/`. 
And all asset and javascript can't be load. Here is a part of caddy log when I try to load `common.js`.
```json
{
  "level": "debug",
  "ts": 1652024296.0010204,
  "logger": "http.log.error",
  "msg": "{id=74d0ejp9f} fileserver.(*FileServer).notFound (staticfiles.go:511): HTTP 404",
  "request": {
    "remote_ip": "someip",
    "remote_port": "someport",
    "proto": "HTTP/2.0",
    "method": "GET",
    "host": "yourls.doamin.com",
    "uri": "/js/common.js?v=1.9",
    "headers": {
      "Sec-Fetch-Mode": ["no-cors"],
      "Sec-Fetch-Dest": ["script"],
      "Accept-Encoding": ["gzip, deflate, br"],
      "Accept-Language": ["ja,en;q=0.9,en-GB;q=0.8,en-US;q=0.7"],
      "Sec-Ch-Ua-Platform": ["\"Windows\""],
      "Purpose": ["prefetch"],
      "Sec-Ch-Ua-Mobile": ["?0"],
      "User-Agent": [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36 Edg/101.0.1210.39"
      ],
      "Accept": ["application/signed-exchange;v=b3;q=0.7,*/*;q=0.8"],
      "Sec-Fetch-Site": ["same-origin"],
      "Referer": ["https://yourls.domain.com/admin/index.php"],
      "Sec-Ch-Ua": [
        "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"101\", \"Microsoft Edge\";v=\"101\""
      ],
      "Dnt": ["1"]
    },
    "tls": {
      "resumed": true,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "h2",
      "server_name": "yourls.domain.com"
    }
  },
  "duration": 0.000419695,
  "status": 404,
  "err_id": "74d0ejp9f",
  "err_trace": "fileserver.(*FileServer).notFound (staticfiles.go:511)"
}
```

Anyone can help?
