### DISCUSSION TITLE
Volume binding persistent data

### DISCUSSION THREAD

**Discussion by Tiritibambix** [YOURLS/YOURLS#3341] [Q&A] [answered]
Hello.

I'm using the basic recommended docker-compose  file like this:
```
version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    ports:
      - 8080:80
    environment:
      YOURLS_DB_PASS: example
      YOURLS_SITE: https://example.com
      YOURLS_USER: example_username
      YOURLS_PASS: example_password

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: yourls
```

How can I bind volumes for persistent data to be backed up, and to find ```user/plugins/``` ?
