### DISCUSSION TITLE
docker-compose another port

### DISCUSSION THREAD

**Discussion by IgorKha** [YOURLS/YOURLS#3411] [Q&A]
Hello! If i try open  https://example.com:8080/admin, i see this: 
![Screenshot_20220819_011029](https://user-images.githubusercontent.com/2268209/185504055-895e8b74-58d4-4105-9606-438d024cd5c3.png)

such a problem if you specify any port other than 80
have any ideas?

## docker-compose.yml

```yaml
version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    ports:
      - 8080:80
    environment:
      YOURLS_DB_PASS: example
      YOURLS_SITE: https://example.com
      YOURLS_USER: example_username
      YOURLS_PASS: example_password

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: yourls
  ```
