### DISCUSSION TITLE
docker-compose Cannot connect to mysql (or external sites at all?)

### DISCUSSION THREAD

**Discussion by xlorepdarkhelm** [YOURLS/YOURLS#3421] [Q&A]
This seems like it should be obvious, but I can't seem to get it to work.

I am trying to get YOURLS up and running with the following docker-compose.yml:

```yaml
---
version: '3.9'

services:
  yourls:
    image: yourls
    restart: always
    ports:
      - 8082:80
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      YOURLS_DB_USER: yourls
      YOURLS_DB_PASS: NotOnYourLife
      YOURLS_DB_HOST: mysql
      YOURLS_SITE: https://my-site.org
      YOURLS_PRIVATE: true
      YOURLS_USER: myuser
      YOURLS_PASS: YeahRight
      YOURLS_COOKIEKEY: "SomethingGoesHere"
      YOURLS_URL_CONVERT: 62
    links:
      - mysql

  mysql:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    healthcheck:
      test: mysql -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD --execute "SHOW DATABASES;"
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER: yourls
      MYSQL_PASSWORD: NotOnYourLife
      MYSQL_DATABASE: yourls
      MYSQL_ROOT_PASSWORD: HaharightlikeIwouldsharethis
```

When I do a `docker compose up` on this, it looks like everything works. When I go to "https://my-site.org/admin" I get the following error:

Fatal error
Incorrect DB config, or could not connect to DB
PDOException: SQLSTATE[HY000] [2002] Connection timed out

I am willing to accept that I misconfigured *something*, but I can't for the life of me figure it out.

If I go into the docker image for yourls, I can't even do an "apt update" as there is no successful connection to update apt, much less be able to install anything to help me diagnose the problem further.

please help.
