### DISCUSSION TITLE
SSL https failing with docker yourls

### DISCUSSION THREAD

**Discussion by necarnot** [YOURLS/YOURLS#3457] [Q&A] [answered]
Hello,

I have successfully set up a docker stack containing a yourls container and a mysql container.
Everything is working fine as long as I'm using simple http, but when trying to go secure (httpS) : 
- though both containers are starting correctly (I can docker exec inside of them and wander around), browsing to https://myyourls.net/admin is failing with no apparent attempt to even connect to any process
- indeed, when looking (docker exec blahblah) at the /etc/apache2/*/* setup, I see no trace of anything related to ssl (for instance, no ssl mod loaded, no sites-enabled/something_related_to_ssl linked, and so on...)

It is becoming clear that I'm missing something obvious in this docker setup. Though I read the docs 128 times, I still can't figure out by which magic one could define YOURLS_SITE: https://myyourls.net yet having an apache setup with nothing related to httpS setup neither working.

Here is my docker-compose.yml if that can help you help me : 

```yml
services:
  yourls:
    container_name: yourls
    image: yourls
    networks:
      backend:
      frontend:
        ipv4_address: 192.168.42.7
    ports:
      - 443:443
    restart: unless-stopped
    environment:
      YOURLS_DB_PASS: xxx
      YOURLS_DEBUG: false
      YOURLS_SITE: https://myyourls.net
      YOURLS_ADMIN_SSL: true
      YOURLS_USER: admin
      YOURLS_PASS: xxx
      YOURLS_DB_HOST: yourls-mysql
      YOURLS_DB_NAME: yourls
      YOURLS_DB_USER: root

  yourls-mysql:
    container_name: yourls-mysql
    image: mysql
    networks:
      backend:
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_DATABASE=yourls
    volumes:
      - /home/someone/yourls_db_volume:/var/lib/mysql

networks:
  backend:
    name: yourls_backend
  frontend:
    external: true
    name: pub_net
```

When scanning ports from a remote host in the same LAN, I see only one port 80 open, and no 443.

I guess this is part of the issue, but that doesn't explain the lack of setup in apache.

Thanks for any hint.

Nicolas
