### DISCUSSION TITLE
Could Not Get Yourls LocalHost to Run with Docker Compose

### DISCUSSION THREAD

**Discussion by MatthewGerges** [YOURLS/YOURLS#3596] [Q&A]
Hi, for context all I am trying to do is to find an open-source way to use an API that creates redirect links that have an original URL. I then want to use the API to keep the branded redirect link the same but change what it directs to (i.e. change the original URL). To do so I am trying to set up Yourls on localhost:8080/admin as a first step but I am running into problems. What I did was I went to this site: https://hub.docker.com/_/yourls and tried copying the docker-compose.yml file to my own. Using Ubuntu 22.04.2 terminal on a Windows machine, I cd'd to the location where I have the dockercompose.yml file and I ran docker-compose up -d which didn't show me any errors in my terminal but when I visited localhost:8080/admin on my machine, the webpage showed me the following error:
![image](https://github.com/YOURLS/YOURLS/assets/82429124/938f9364-f7cc-4b0b-9185-a09528bac092)

Below is my docker-compose.yml file:
```
version: '3.1'

services:
  yourls:
    image: yourls
    restart: always
    ports:
      - 8080:80
    environment:
      YOURLS_DB_HOST: teescanlinks.mysql.database.azure.com
      YOURLS_DB_USER: UsernameIUseToSignInToMySQLDatabaseOnAzure
      YOURLS_DB_PASS: PWD
      YOURLS_DB_NAME: teescanlinks
      YOURLS_SITE: https://tshirtscanner.com
      YOURLS_USER: MatthewGerges
      YOURLS_PASS: Yuiy_8976
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PWD
      MYSQL_DATABASE: teescanlinks
      MYSQL_USER: MatthewGerges
      MYSQL_PASSWORD: PWD
```

I also tried using the docker run command as well but also ran into errors doing that: ```docker run --name some-yourlss -e YOURLS_DB_HOST=teescanlinks.mysql.database.azure.com \
    -e YOURLS_DB_USER=USER -e YOURLS_DB_PASS=PWD -d yourls ``` This just gave me the following output:
```
bb65614eb00699f50a34d5dae52b59357ca9eb4b6d83c7183c99b0be55478c30
root@LGerges:/mnt/c/users/matth/documents/Flutter App Development/teescanfire/delegation# docker logs some-you
rlss
YOURLS not found in /var/www/html - copying now...
Complete! YOURLS has been successfully copied to /var/www/html
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Thu Jul 27 02:19:57.091227 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Debian) PHP/8.2.8 configured -- resuming normal operations
[Thu Jul 27 02:19:57.091274 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
root@LGerges:/mnt/c/users/matth/documents/Flutter App Development/teescanfire/delegation# docker exec some-yourlss ping teescanlinks.mysql.database.azure.com
OCI runtime exec failed: exec failed: unable to start container process: exec: "ping": executable file not found in $PATH: unknown
```

I would follow the standard installation procedure on here: https://yourls.org/docs/guide/install where you install the latest archive and follow the rest of the steps but the problem is that it requires me to unzip files to my website in the public_html folder (and I don't have a website - I'm doing this from bare scratch - no server or anything which is why I opted to use the docker compose).

Please let me know how to fix the issue or if I am missing something. Also, please advise me on next steps - after I get this running on my local machine, do I need to deploy the docker image to a server to use the API? And what steps would I need to follow in order to do so. Thanks!
