### ISSUE TITLE
"&" in the password bricks the config file (docker)

### ISSUE THREAD

**Issue by JustinGuese** [YOURLS/YOURLS#3302]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

latest

### Description

inserting a password with "&" in the "YOURLS_PASS" as environment variable messes up the config file 

```
yourls_user_passwords = [
    'user' => 'passwordwithoutand getenv_docker('YOURLS_USER') => getenv_docker('YOURLS_PASS'),',
];
```

### Expectation

i guess the & is actually interpreted

### Reproduction steps

set password YOURLS_PASS = sjkdhaadjsk&

### Context

should be fixed/escaped

**Comment by ozh** [comment]
Your code : 

```php
yourls_user_passwords = [
    'user' => 'passwordwithoutand getenv_docker('YOURLS_USER') => getenv_docker('YOURLS_PASS'),',
];
```
Sets a user with username "`user`", and the password is the following string : "`passwordwithoutand getenv_docker('YOURLS_USER') => getenv_docker('YOURLS_PASS'),`", which I'm not sure is what you're trying to achieve.

Chars in passwords are not "escaped" and you can use any char in your passwords, see t[he ones used in unit tests](https://github.com/YOURLS/YOURLS/blob/master/tests/data/config/yourls-tests-config-ci.php#L36-L49).

There is no bug there. If you're not sure about how to use a setting or config, please open a discussion instead.

**Comment by JustinGuese** [comment]
Hey @ozh, the code snippet is the result of the config file that is auto-generated if you would set the environment variables
- YOULRS_USER="user"
- YOURLS_PASS="passwordwithoutand&"

using these settings the docker images fails and just prints a php error, which is due - i guess - to the config.php being generated in a wrong way

i solved it by using another password without "&", and it works now, so i don't care what you do with this information. but i thought you might be interested in this bug, but sure just leave the bug in

**Comment by JustinGuese** [comment]
if you want to reproduce:

```
version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    ports:
      - 8080:80
    environment:
      YOURLS_DB_PASS: example
      YOURLS_SITE: http://localhost:8080/
      YOURLS_USER: example_username
      YOURLS_PASS: "example_password&"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: yourls
```

localhost:8080/admin

_Parse error: syntax error, unexpected identifier "YOURLS_USER", expecting "]" in /var/www/html/user/config.php on line 75_
