### ISSUE TITLE
After update to 1.10.0 white page get´s loaded

### ISSUE THREAD

**Issue by scharez** [YOURLS/YOURLS#3891]
### Self troubleshooting

- [x] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [x] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.10.0

### Description

I am using docker-compose and updated yourls in my yaml file and restarted the docker-compose stack. 

Do I have to upload the new files to the docker container volume?

```
version: '3.1'

volumes:
  yourls-db:
    name: yourls-db

networks:
  default:
    name: yourls-network
  proxy-network:
    external: true

services:

  yourls:
    image: yourls:1.9.2
    container_name: yourls-app
    restart: always
    environment:
      YOURLS_DB_PASS: yourls
      YOURLS_SITE: https://go.domain.at
      YOURLS_USER: admin
      YOURLS_PASS: somePassword
    volumes:
     - /opt/yourls:/var/www/html
    depends_on:
      - mysql
    networks:
      - default
      - proxy-network

  mysql:
    image: mysql:8.0
    container_name: yourls-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourls
      MYSQL_DATABASE: yourls           
    volumes:
      - yourls-db:/var/lib/mysql
    networks:
      - default

```

 - In the docker logs no error at all
 - In the browser dev tools, nothing gets loaded 
 - I am using to plugins

<img width="1417" alt="Image" src="https://github.com/user-attachments/assets/3d478052-ef18-4e06-b63e-a2999e11b129" />

### Context

_No response
